SELECT COUNT(*) TOTAL_NUMBER, MAKE, MIN(PRICE), MAX(PRICE), AVG(PRICE), SUM(VIEW_COUNT), SUM(VIEW_COUNT)/COUNT(*) AVG_VIEWS, SUM(CASE  WHEN SOLD = TRUE THEN 1 ELSE 0 END) SALES
FROM "db_data"."VehicleRecords"
WHERE PRICE > 0 AND PRICE < 300000 AND SOLD = TRUE and YEAR > 1999
GROUP BY MAKE 
ORDER BY TOTAL_NUMBER DESC